### PR TITLE
add - DiffNode has been added

### PR DESCRIPTION
**Pull request by viclovsky**
https://github.com/lukas-krecan/JsonUnit/issues/109

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Thanks, will look at it some day this week

**Comment by lukas-krecan** [comment]
Thanks again, I really appreciate your effort. Since the PR exposes some internal classes and adds quite a lot of complexity I am reluctant to merge it. I am trying to keep the API as small as possible to enable future changes. First of all, I'd like to understand you use-case. What do you mean by customizing the output? Why can't you do it on exception handling level (in testing framework)? Would adding configuration info to the exception help?

**Comment by viclovsky** [comment]
I use JsonUnit not only for unit testing but also for regression testing. 
Let me explain use case. It isn’t convenient to use diff in text format (exception format) when we compare big Jsons. Sometimes more useful and obvious to see visually how they different. For instance, diff might look like this:  jsondiffpatch 2018-05-29 13-42-01 Such cool diff can be done by [jsondiffpatch](https://github.com/benjamine/jsondiffpatch) or unified diff  [diff2html](https://github.com/rtfpessoa/diff2html) 
And it is more clearly and visully. 
The main thing is that they use different formats. Therefore it is necessary to customise output by implementing special filter. Diff should be in format (see class  [DiffNode](https://github.com/lukas-krecan/JsonUnit/pull/113/files#diff-c486a0d203d67b4964154c50cbec94a9)) to be able easy and smoothly adopt it to any util (jsondiffpatch/diff2html). The scheme here is: {Node actual, Node expected, List<NodeDiff>, ... other} -> {special format for html (jsondiffpatch/diff2html)} -> html
And it can’t be done by using exceptions (not enough information). If you know how I can do it please let me know.

**Comment by lukas-krecan** [comment]
Thanks, now I understand. I have been thinking about creating a subclass of AssertionError and add the information in there. Filters are natural for request response frameworks but I feel they do not fit into JsonUnit. I have some changes I'd like to do first but as soon as I have some prototype, I will let you know. I really appreciate your effort, bit it will be me who will maintain the library so I need to feel ok about the changes.

**Comment by lukas-krecan** [comment]
Hi, I have played with your PR and came up with this https://github.com/lukas-krecan/JsonUnit/pull/115 would it be usable for your  use-case or do you need to add anything else?

**Comment by lukas-krecan** [comment]
Merged as part o #115

**Pull request closed without merging**
