### PR TITLE
enable GitHub Actions workflow (ci.yml)

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Hi, thanks. What's the advantage over Travis build https://travis-ci.org/lukas-krecan/JsonUnit ?

**Comment by sullis** [comment]
> Hi, thanks. What's the advantage over Travis build https://travis-ci.org/lukas-krecan/JsonUnit ?

in my experience, GitHub Actions executes builds faster than TravisCI.

**Comment by lukas-krecan** [comment]
Ok, let's try it. Thanks

**Comment by Automobileservices4** [comment]
#222

**Pull request merged**
