### PR TITLE
Add path options

### PR DESCRIPTION
**Pull request by Vladiatro**
I need to compare large JSONs with some arrays being order-sensitive, while some of them (e.g. inner ones) being insensitive. This PR adds an ability to apply options to specific paths with ability to make with this `when()` something more in the future.
Format: `when(path("root.array"), then(IGNORING_ARRAY_ORDER))`.
Example:
```java
assertThatJson("{\"obj\":{\"a\": [1, 2], \"b\": [3, 4]}}")
            .when(path("obj.a"), then(IGNORING_ARRAY_ORDER))
            .isEqualTo("{\"obj\":{\"a\": [2, 1], \"b\": [3, 4]}}");
assertThatJson("[{\"b\":[4,5,6]},{\"b\":[1,2,3]}]")
            .when(IGNORING_ARRAY_ORDER)
            .when(path("[*].b"), thenNot(IGNORING_ARRAY_ORDER))
            .isEqualTo("[{\"b\":[1,2,3]},{\"b\":[4,5,6]}]");
```

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Hi, thanks a lot. It looks intriguing. It will take me some time to process it, though.

**Comment by lukas-krecan** [comment]
This is going to be a hard decision. On one hand I like the PR code, it's nice, elegant and well isolated. On the other hand, I am quite reluctant to add complex new features to JsonUnit since it is already quite feature-heavy and it's increasingly harder to add new stuff. As an example I can mention JsonPath support. I have added JsonPath support few releases back and since then people (understandingly) expect JsonPath to work everywhere (#198). So if we were to include this feature, we should add support for JsonPath to `when(path("[*].b"), ...` method as well.

But before that I have to decide if I am brave enough to add the feature at all. I am afraid that the project is approaching its complexity limit.

As an alternative we could use this approach https://github.com/lukas-krecan/JsonUnit/pull/204/files which is less elegant and more cumbersome but it's much more easier to implement.

Please give me few days to make my mind.

**Comment by lukas-krecan** [comment]
One more thing. If I am not mistaken, we would have to deal with overlapping paths, would not we?

**Comment by Vladiatro** [comment]
Hi Lukáš. We use REST integration tests with direct JSON comparisons to server responses. These JSONs are large, so it would take much time to manually describe all the JSON parts, and compare it with many assertions. It is a great ability to treat arrays as sets, but some arrays are not sets, so path options would be a very nice feature. Also `when()` with `thenIgnore()` can replace `whenIgnoringPaths()`, possibly some other things.
Yes, I have overlapping support: https://github.com/lukas-krecan/JsonUnit/pull/205/files#diff-b77b022fb6e47e0b0ad18369d030b706R1298. I thought I couldn't avoid this, especially with JsonPath, so it's better to define overlapping behaviour that somehow prohibit or deprecate it. Now it takes the last when() call that matches current path.

**Comment by Vladiatro** [comment]
And JsonPath surely should be added. I can do it if you are leaning towards to add when(path()).

**Comment by lukas-krecan** [comment]
Please wait, I will think about it for few days. Thanks for understanding

**Comment by lukas-krecan** [comment]
I have decided to merge it after all. I will just simplify it a bit, if you do not mind. Thanks again.

**Pull request merged**
