### PR TITLE
Add example of how to do a custom matcher on two values

### PR DESCRIPTION
**Pull request by xpmatteo**
Matching that a number is between an upper and lower bound is something that is probably needed by people other than me.

The software supports this use case, but I did not find it entirely obvious how to do it; I hope this makes it clear!

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Hi, thanks a lot. I am afraid that it would make already long section about custom matchers even longer. Can you please self-answer the question on stackoverflow and just add a link here?

**Comment by xpmatteo** [comment]
I was not coming from a question on stackoverflow.  Did you have a specific question in mind?

**Comment by lukas-krecan** [comment]
Sorry, I thought that it would be great to ask the question on StackOverflow, answer it at once and then link it from Readme. I can do it, if you want.

**Comment by lukas-krecan** [comment]
I put the question with answer on SO and linked it from README https://stackoverflow.com/questions/66183628/how-to-create-a-matcher-in-jsonunit-with-more-than-one-parameter/66183629#66183629 Thanks

**Pull request closed without merging**
