### PR TITLE
Source for actual and expected json has been added to DifferenceListe…

### PR DESCRIPTION
**Pull request by viclovsky**
Hi, Lucas

I haven't found the way to get actual and expected json source from current listener signature. 
The only way to do it is to set it in overrided class `.withDifferenceListener(listener.setActual(actual).setExpected(expected)));`
 Which doesn't look good... For our ease I suggest to add it into DifferenceListener. What do think about it?

### CODE REVIEW

**Comment by lukas-krecan** [comment]
The trouble is that this is backward incompatible change. I assume that you are so far the only user of the feature so we can do it, but in the future I would hesitate more.

There several options
1. Instead of adding Object actualSource, Object expectedSource add one interface (let's call it DifferenceContext for lack of a better name) where we could add other stuff in the future
2. Add getActualSource and getExpectedSource to Difference interface
3. Or add DifferenceContext to Difference interface

I am not sure which one is the best, 2. 3. do not break backward compatibility but are less clean. On the other hand, there already is Difference.getConfiguration which would belong to the DifferenceContext

**Comment by viclovsky** [comment]
Let's do first option as it is more clear and user-friendly while we have such opportunity and it won't cost us so much by breaking compatibility.

**Comment by lukas-krecan** [comment]
Thanks

**Comment by lukas-krecan** [comment]
Released as 1.31.0

**Pull request merged**
