### PR TITLE
Upgrade to Hamcrest 2.1

### LINKED ISSUE #190: Upgrade hamcrest to 2.x
Project currently uses 1.x version of hamcrest

### PR DESCRIPTION
**Pull request by valfirst**
Fixes #190

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Thanks a lot, I will take a look at it in next week or two.

**Comment by lukas-krecan** [comment]
Hi, thanks again. I have a simplified PR #199. The main differences are
1) It keeps using deprecated `hamcrest-core` and `hamcrest-library` dependencies. I'd like to prevent duplicate imports of both Hamcrest versions in case someone has explicit dependency on Hamcrest 1
2) `JsonPartMatcher` stores differences between `doMatch` and `describeMismatch` calls so multiple comparisons are not needed

**Comment by valfirst** [comment]
Hi @lukas-krecan 

1. Sounds reasonable.
2. Regarding this point I had doubts as well: keep differences or perform repetitive comparisons

For me your PR looks good, I think you can close this PR and merge yours

Thanks

**Comment by lukas-krecan** [comment]
Replaced by #199

**Pull request closed without merging**
